version: '2'
services:
  webserver:
    image: phpstorm/php-71-apache-xdebug-26
#    ports:
#      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=composer-test.enomis.dev
#      XDEBUG_CONFIG=remote_enable=1 remote_host=host.docker.internal remote_port=9000 remote_autostart=1
      #            - XDEBUG_CONFIG=remote_enable=1 remote_host=host.docker.internal remote_port=9000
